### ISSUE TITLE
Generate and update a tracking issue

### ISSUE THREAD

**Issue by MTRNord** [MTRNord/zola-check-manager#4]
It would be nice to have an additional issue for tracking faulty links outside just annotations.

Possible features to add to this in a milestone 2:

- [ ] Suppressing alerts by ticking a checkbox in future runs
- [ ] Pinging teams/people on new links
- [ ] Pinging teams/people on newly available web archive links.
